### ISSUE TITLE
Is it normal for Vth to be less than 0 after training?

### ISSUE THREAD

**Issue by MuscleGood** [Ikarosy/Gated-LIF#2]
Hi, I'd like to know that whether it is normal for Vth to be less than 0 after training. I trained the model with your code and found the result reaches the expectation while some of the Vth are less than 0. Thank you in advance!

**Comment by Ikarosy** [comment]
Vth along with all other membrane-related parameters is bounded within (0,1) through the sigmoid. Double check whether the Vth you saw was originally from the model checkpoint or from the sigmoid.


发件人：SpikingGood ***@***.***>
发送日期：2023-06-08 11:49:00
收件人：Ikarosy/Gated-LIF ***@***.***>
抄送人：
主 题：[Ikarosy/Gated-LIF] Is it normal for Vth to be less than 0 after training? (Issue #2)

Hi, I'd like to know that whether it is normal for Vth to be less than 0 after training. I trained the model with your code and found the result reaches the expectation while some of the Vth are less than 0. Thank you in advance!
